### ISSUE TITLE
YouTube links not working

### ISSUE THREAD

**Issue by D1reW0lf** [vleeuwenmenno/songguru-bot#39]
Hi. 

I tried to use SongGuru with the following link either automatically and tagging the bot but neither worked.

https://youtu.be/Q0oIoR9mLwc?si=HQXsM6ibdV4QM0cy

**Comment by vleeuwenmenno** [comment]
Currently another issue that might be related https://github.com/vleeuwenmenno/songguru-bot/issues/40
